ant-design/antd-tools

lib/getTSCommonConfig.js

支持以下写法：
```jsx
import React from 'react';
```

chore: enable allowSyntheticDefaultImports

---

lib/gulpfile.js
lib/tslint.json

ref: https://github.com/ant-design/ant-design-mobile/pull/477

fix: should lint success

---

lib/getWebpackConfig.js
package.json

Object.assign 会导致修改 `webpackConfig`  里的内容的时候把 `uncompressedWebpackConfig` 里的内容也修改掉。
比如这里 https://github.com/ant-design/ant-design/blob/master/webpack.config.js#L15-L18 其实会在 `uncompressedWebpackConfig` 塞两个 `es3ify-loader` 进去。

Replace assign with deepAssign

---

package.json

antd-tools [依赖](https://github.com/ant-design/antd-tools/blob/master/lib/getWebpackConfig.js#L26) 它，但是却写在 antd 的 devDependencies  里。

Add babel-plugin-import to dependencies

---

lib/tslint.json

https://github.com/palantir/tslint-react/issues/79
先关闭 jsx-wrap-multiline，以便于趁早把 https://github.com/ant-design/ant-design-mobile/pull/1051  
合并

fix: jsx-wrap-multiline

---

package.json

https://github.com/ant-design/antd-tools/blob/b7c7a4f6503eb2e3e7eb07f6ffe2d2412493e3b3/lib/gulpfile.js#L32
devDeps won't be install.

fix: rimraf should be deps.

---

package.json

[ant-design](https://github.com/ant-design/ant-design/blob/master/package.json#L141) & [ant-design-mobile](https://github.com/ant-design/ant-design-mobile/blob/master/package.json#L123) 都已经自行声明了对 typescript 的依赖，所以可以吧 antd-tools 里的依赖修改为 peerDependencies，这样以后升级 typescript 也比较方便。

deps: move typescript to peerDependencies

---

lib/gulpfile.js
lib/utils/getChangelog.js
package.json

发布时自动创建 GitHub release。
需要先在 GitHub 上[创建一个 token](https://github.com/settings/tokens)，钩上 `repo.public_repo`。
在 `~/.zshrc` 或 `~/.bashrc` 里加上:
```bash
export GITHUB_TOKE=创建的 token
```
`npm run pub` 时会自动从 CHAGELOG 里读内容创建 release。

Create GitHub release

---

lib/tslint.json

Otherwise it will complain `...rest` needs a trailing comma

fix: tslint trailling-comma rule needs to be esSpecCompliant

---

lib/getWebpackConfig.js

When I use antd-tools in a project whose pkg.name !== 'antd', it will cause an error in babel's duplicate plugin verification.
```
// babel import for components
babelConfig.plugins.push([
resolve('babel-plugin-import'),
{
style: true,
libraryName: pkg.name,
libraryDirectory: 'components',
},
]);
// Other package
if (pkg.name !== 'antd') {
babelConfig.plugins.push([
resolve('babel-plugin-import'), // duplicate import 'babel-plugin-import' plugin without unique name
{
style: 'css',
libraryDirectory: 'es',
libraryName: 'antd',
},
]);
}
```
[antd-tools code](https://github.com/ant-design/antd-tools/blob/e0242e06c53c243554ef5d21b3f9dafa7160c1f5/lib/getWebpackConfig.js#L45)
[babel code](https://github.com/babel/babel/blob/3a399d1eb907df520f2b85bf9ddbc6533e256f6d/packages/babel-core/src/config/c …

fix babel7 duplicate plugin verification

---

lib/getWebpackConfig.js
lib/gulpfile.js
lib/lint/checkDeps.js

Current logic will tag whatever npm publish success or not.

Do not tag if parent cmd failed

---

lib/gulpfile.js
lib/lint/checkDiff.js
lib/utils/projectHelper.js
package.json

为了解决 #95 做了两件事情：
1. 添加一个 `.antd-tools.config.js` 配置文件支持，允许用户执行 `dist` 后运行额外的脚本。这样可以保证 dist 后执行额外的 index.less 文件生成。
2. 添加一个 `diff lint`，会从 `unpkg` 中拉取最新的文件列表。如果发现文件丢失，会暂停流程询问发布人员是否是故意的。直到发布人员明确输入 `YES` or `NO` 才会继续执行。

Add dist finalize script & support package file diff

---

lib/jest/demoPreprocessor.js

修复 antd 测试 warning：
```
This problem is likely caused by another plugin injecting
"__Demo" without registering it in the scope tracker. If you are the author
of that plugin, please use "scope.registerDeclaration(declarationPath)".
The exported identifier "__Demo" is not declared in Babel's scope tracker
as a JavaScript value binding, and "@babel/plugin-transform-typescript"
never encountered it as a TypeScript type declaration.
It will be treated as a JavaScript value.
```

Fix antd test warning `__Demo`

---

lib/gulpfile.js
package.json

看了一圈似乎 npm 没有这个配置，在 `.antd-tools.config.js` 添加一个 `tag` 属性支持。

support config tag

---

package.json

As its try to get antd-tools/lib/getBabelCommonConfig.js
I think its should explicit declaration in package.json
Then its can fix miss dependency in ant-design which try to run compile

Add @babel/plugin-transform-typescript in package.json

---

lib/getWebpackConfig.js

In the `ant-design` main repository the response of `getWebpackConfig` is expected to be an array:
https://github.com/ant-design/ant-design/blob/9b6db94fdf1cd0cda0f3de0a1f127ac6fd2fc77d/webpack.config.js#L89
It's using `forEach` on it and also it's spread in module.exports further down:
https://github.com/ant-design/ant-design/blob/9b6db94fdf1cd0cda0f3de0a1f127ac6fd2fc77d/webpack.config.js#L120
If the environment variable `RUN_ENV` is not `PRODUCTION` though, it's returning the config object and no array.
This PR fixes this inconsistency which breaks the build in case `RUN_ENV` is not `PRODUCTION`, see error below:
```
webpackConfig.forEach is not a function
at Object.<anonymous> (/.../ant-design/webpack.config.js:89:15)
```
I checked the use of `getWebpackConfig` in the main repo and it …

fix getWebpackConfig response if RUN_ENV is not dev

---

lib/gulpfile.js
lib/transformLess.js
package.json

编译时读取配置文件生成对应 css 文件。要和 webpack 区分开需要额外注入。先别合，我看看有没有更好的方式。
-------------
Update: 移除了 `compile:less`，需要发个大版本

feat: support read less opt

---

lib/getWebpackConfig.js

在 Next.js 中使用 antd v5 出现错误：[ReferenceError: window is not defined](https://github.com/ant-design/ant-design/discussions/36814#discussioncomment-3293917)。排查发现，[v5 移除 lib 产物](https://github.com/ant-design/ant-design/pull/36362)，仅提供 es 产物、 dist 产物（UMD）。webpack 4 构建时， `output.globalObject` 默认是 `window` ，而 node 没有 `window` 顶层对象，导致出现该错误。
ref:
- [webpack output.globalObject](https://webpack.js.org/configuration/output/#outputglobalobject)
- [Can't create UMD build which can be required by Node · Issue #6522 · webpack/webpack · GitHub](https://github.com/webpack/webpack/issues/6522)

feat: support for UMD bundles to be used on the ssr

---

lib/gulpfile.js
package.json

新增语言包编译流程：
1. 仅打包 `components/locale` 到 `locale` 目录。
2. 内部依赖（如：`components/calendar/locale`）一起打包进来，外部依赖保持 external（如： `rc-pagination/lib/locale`）。
3. es 产物不再打包 `locale` 相关文件。
实现过程中遇到的两个问题：
1. father 暂不支持修改 esbuild 配置，打包无法达成上述预期。原本提了个 [PR feat: support configuring esbuild](https://github.com/umijs/father/pull/538)，后来和辟起讨论过程中，计划是通过插件机制去修改，但预计没那么快。目前是直接用 father 内部依赖的 esbuild 来打包，后续实现插件制特性后，可以快速迁移。
2. TypeScript 仅生成 `components/locale` 目录的类型声明文件，但语言包内部引用了其他文件，导致生成的类型文件有问题，暂没有找到 TypeScript 支持配置修改依赖解析路径。目前是写的硬代码，类型从 `es/locale-provider` 引用。
这两个问题，不知道有没更好的解决方式 : D
ref: 
- [[RFC] Provide commonjs locale file in v5](https://github.com/ant-design/ant-design/discussions/38107)
- [issues: ReferenceError: window is not defined after upgrading from v4 to v5 in …

feat: compile locale files

---

lib/getBabelCommonConfig.js
package.json

fixed: https://github.com/ant-design/ant-design/actions/runs/3511777282/jobs/5882875095
原因分析：https://github.com/ant-design/ant-design/pull/38779/files 改变了 browserlist 的兼容版本
参考 https://github.com/babel/babel/pull/13075/files 变更的配置，可以推测当 babel preset env 设置的 browerlist 版本较新时，是不会编译 class 下的 `super(...arguments)` 语法的，需要配合 `@babel/plugin-transform-classes`，这样将 class 转为 function 后，就可以继续处理了
在 babeljs.io 的 playground 验证如下
不加 `@babel/plugin-transform-classes` 报错
加 `@babel/plugin-transform-classes` 后编译成功
related: https://github.com/babel/babel/pull/12722

fix: add @babel/plugin-transform-classes

---

lib/sortApiTable.js

这么好的东西居然没发现，准备搞 v6 的话，可以用这个工具再统一处理一次 api table 的顺序

feat(sortApiTable): support process deprecated props

---

package.json
src/lint/checkDiff.ts

当前 package-diff 只检查了缺失部分，并没有检查有哪些新增。比如[ antd-mobile 5.39.0 出现了意外的产物](https://npmmirror.com/package/antd-mobile/files/cjs/components/ellipsis/~ellipsis.js?version=5.39.0)
一方便需要担心敏感信息泄漏，另一方便可能会导致 breakchange？本次 PR 加入了新增和差异检查。
（或许可以再加一个开关控制是否检查新增）

feat: enhance file list fetching with Arborist and npm-packlist
