ant-design/antd-tools

- lib/gulpfile.js
- package.json
> Add hot reload, close #1

- lib/gulpfile.js
- package.json
> Add dora-plugin-upload

- lib/getWebpackConfig.js
- package.json
https://github.com/ant-design/ant-design/issues/1561
> Feat dist banner

- lib/runCmd.js
- lib/runCmdWithOut.js
- lib/utils/getRunCmdEnv.js
https://github.com/ant-design/ant-design/issues/1807#issuecomment-221308998
> fix: make sure node_modules/.bin in the PATH

- lib/getWebpackConfig.js
refer to [#1970](https://github.com/ant-design/ant-design/issues/1970)
将 IE8 相关配置挪到 antd 项目中自己实现
> remove IE8 related config

- lib/tslint.json
https://github.com/ant-design/ant-design/pull/3888#issuecomment-261199346
顺便发个新版本吧
> Disable jsx-no-lambda

- package.json
https://github.com/ant-design/ant-design/issues/5016
> upgrade typescript to 2.2.1

- package.json
https://github.com/ant-design/ant-design-mobile/issues/1015
> feat: upgrade gulp-typescript

- lib/gulpfile.js
- lib/runCmd.js
- package.json
使用rimraf模块 替换 rm -rf 命令，修复 spawn atool-build ENOENT 错误
> add rimraf module and update spawn atool-build ENOENT

- lib/getBabelCommonConfig.js
- lib/getWebpackConfig.js
- lib/gulpfile.js
- package.json
Close: https://github.com/ant-design/antd-tools/issues/39
npm link 调试时报出其他错误：
```sh
antd-tools run compile-with-es
/bin/sh: rimraf: command not found
```
@benjycui 跟进看下
> [WIP] add es support, ref #39

- lib/getWebpackConfig.js
- lib/gulpfile.js
- lib/replaceLib.js
- package.json
See https://github.com/ant-design/ant-design/issues/6310#issuecomment-305176273 and https://github.com/ant-design/ant-design/commit/0080b6ddf5bae47531f3429d4680c37d45513d37#commitcomment-22345793
> Use babel for module path replacement

- lib/getBabelCommonConfig.js
- package.json
ref https://github.com/react-component/rc-tools/pull/36/files
> feat: polyfill assign

- lib/getBabelCommonConfig.js
- lib/jest/codePreprocessor.js
- lib/jest/demoPreprocessor.js
- lib/jest/rewriteSource.js
- package.json
把原来 antd-demo-jest 的内容放到这里，原来只要处理 demo，现在组件代码也需要处理，还是放在这里比较合适。
> Add jest preprocessors

- README.md
- lib/gulpfile.js
- package.json
data-picker haven't build style/css.js https://github.com/ant-design/antd-tools/commit/fcce754786a701cca5e1f42eaaead90ef00ea49a#commitcomment-23942933
https://unpkg.com/antd-mobile@2.0.0-alpha.7/lib/date-picker/style/
https://unpkg.com/antd-mobile@1.6.5/lib/date-picker/style/
> fix: remove .web staff

- package.json
https://github.com/ant-design/ant-design/pull/9527#issuecomment-370654028
https://github.com/facebook/jest/issues/5119
Fix  `jest-environment-node` path resolve.
```
antd@3.2.3 /Users/afc163/Projects/ant-design
├─┬ antd-tools@5.1.1
│ └─┬ ts-jest@21.2.4
│   └─┬ jest-config@21.2.1
│     └── jest-environment-node@21.2.1 
├─┬ jest@22.4.2
│ └─┬ jest-cli@22.4.2
│   ├─┬ jest-config@22.4.2
│   │ └── jest-environment-node@22.4.1 
│   ├─┬ jest-runner@22.4.2
│   │ └─┬ jest-config@22.4.2
│   │   └── jest-environment-node@22.4.1 
│   └─┬ jest-runtime@22.4.2
│     └─┬ jest-config@22.4.2
│       └── jest-environment-node@22.4.1 
└─┬ lint-staged@7.0.0
└─┬ jest-validate@22.4.2
└─┬ jest-config@22.4.2
└── jest-environment-node@22.4.1 
```
> upgrade ts-jest

- lib/tslint.json
- package.json
支持 prettier！
删除了大部分格式化规则，交给 prettier 来支持
> Support prettier

- lib/getWebpackConfig.js
- package.json
使用进度条来显示构建进度。
`antd`上的进度条修改已前向兼容。
> use `webpackbar` rather than `webpack.ProgressPlugin`

- lib/gulpfile.js
希望在 run pub 的时候不自动更新 tag, 和 push
> feat: Add --skip-tag when pub

- lib/utils/getRunCmdEnv.js
Fix #61 
This needs to be tested on mac/linux.
> Fix Windows path issue on getRunCmdEnv

- lib/gulpfile.js
> fix Windows path on gulpfile

- lib/tslint.json
Add prefer-const rule in tslint.json.  Fix problems like https://github.com/ant-design/ant-design/pull/13060
> Add prefer-const

- package.json
This PR is a pre-requirement of ant-design/ant-design#13067.
> chore: upgrade to webpackbar 3.1.2

- lib/tslint.json
添加几个 space 相关的 tslint 的 rule。看起来和 prettier 没有冲突，@chenshuai2144 double confirm 一下。
ref: https://github.com/ant-design/ant-design/pull/13594#discussion_r241293905
> add space related rule

- lib/gulpfile.js
- lib/lint/checkDeps.js
- package.json
Add lint to support check component style dependencies included in `**/style/index.tsx`.
> lint support check style dependencies

- lib/gulpfile.js
- lib/runCmd.js
增加 child_process.spawn() 在 windows 环境下的判断
> add compatible with windows platform

- lib/runCmd.js
- package.json
ref: https://github.com/ant-design/antd-tools/pull/97
> fix: node platform judge

- lib/gulpfile.js
> Follow the DRY principle；

- lib/postcssConfig.js
- package.json
ref: https://github.com/ant-design/ant-design/issues/16970
> Suppress autoprefixer warning

- lib/gulpfile.js
- package.json
To close https://github.com/ant-design/ant-design/issues/17655
> feat: add sourcemap for compile

- lib/gulpfile.js
- lib/lint/checkDiff.js
> refactor: Only check current version

- lib/gulpfile.js
- package.json
Remove useless compiled sourcemap file
> chore: Remove sourcemap

- lib/gulpfile.js
Blocking https://github.com/ant-design/ant-design/pull/22953
> Do not compile tests in typescript

- .prettierrc
- lib/getBabelCommonConfig.js
- lib/getNpm.js
- lib/getTSCommonConfig.js
- lib/gulpfile.js
- lib/install.js
- lib/lint/checkDeps.js
- lib/lint/checkDiff.js
- lib/updateComponents.js
- lib/utils/getRunCmdEnv.js
- lib/utils/projectHelper.js
- package.json
ref: https://github.com/ant-design/ant-design/pull/24327
有单独使用样式文件的需求，run dist 太费，docker 跑不动……
> Add compile less

- lib/sortApiTable.js
导出一份 API 列表供分析用
ref https://github.com/ant-design/ant-design/issues/28654
> feat: report api list

- lib/replaceLib.js
https://github.com/react-component/image/blob/16462632c3ccd04d439586ac120f7e3a4c5b9af3/src/Preview.tsx#L3-L9
Image 里这些 icons 也需要拆分到 antd 上层来。
> replace antd icons esm path

- lib/getBabelCommonConfig.js
fixes https://github.com/ant-design/ant-design/issues/28804
> fix  useESModules judgement

- lib/gulpfile.js
`gulp-strip` 截取失败是因为 ts 编译的时候把 `/* ... */` 摘除了，前置一下 strip 提前做清理即可。
> fix: strip before ts compile

- lib/getBabelCommonConfig.js
- lib/utils/projectHelper.js
for https://github.com/ant-design/ant-design/pull/29885
> feat: add BrowserslistConfig detect

- lib/utils/getRunCmdEnv.js
> fix Windows path on getRunCmdEnv

- lib/jest/codePreprocessor.js
- lib/jest/demoPreprocessor.js
- package.json
https://github.com/facebook/jest/pull/10834
https://github.com/ant-design/ant-design/pull/30783
> test: upgrade to jest 27

- lib/lint/checkDeps.js
- lib/utils/getRunCmdEnv.js
检查 `@ant-design/icons` or `lodash` 是否被全量代码引入。
ref https://github.com/ant-design/ant-design/issues/31008
> feat: Check deps

- lib/lint/checkDeps.js
support `// deps-lint-skip-all` to disable style deps check
ref https://github.com/ant-design/ant-design/pull/33890
> feat: deps check can skip all comment

- lib/getBabelCommonConfig.js
- package.json
https://github.com/ant-design/ant-design/pull/38779
> fix: add @babel/plugin-transform-classes and remove unused babel plugins

- lib/gulpfile.js
> fix: Incorrect logic for inserting `"use client"`

- lib/getWebpackConfig.js
- package.json
https://github.com/webpack/webpack.js.org/issues/4837#issuecomment-816754861
> fix: rm ModuleConcatenationPlugin

- package.json
- src/jest/imagePreprocessor.ts
ref https://github.com/ant-design/ant-design/actions/runs/14221492334/job/39850417330?pr=53390
> fix: jest parser
